name: solar_training
channels:
- anaconda
- conda-forge
dependencies:
- python=3.7 
- pip=20.2.4
- pip:
  - matplotlib>=3.3,<3.4
  - psutil>=5.8,<5.9
  - tqdm>=4.59,<4.60
  - pandas>=1.1,<1.2
  - scipy>=1.5,<1.6
  - numpy>=1.10,<1.20
  - rasterio==1.2.10
  - ipykernel~=6.0
  - azureml-core==1.37.0
  - azure-storage-blob==12.9.0
  - azureml-defaults==1.37.0
  - azureml-mlflow==1.37.0
  - azureml-telemetry==1.37.0
  - tensorboard==2.4.0
  - tensorflow-gpu==2.4.1
  - tensorflow-datasets==4.3.0
  - onnxruntime-gpu>=1.7,<1.8
  - horovod[tensorflow-gpu]==0.21.3

